name: Github secrets

on:
    workflow_dispatch: 

jobs:
    deployment:
        runs-on: windows-latest
        steps:
            - name: Print secret
              run : |
                echo "MY_SECRET_VALUE: ${{secrets.MY_SECRET_VALUE}}"
                echo "i_dont_exist: ${{secrets.i_dont_exist}}"

            - name : Print secret after copying into env variable
              run : |
                  echo "MY_SECRET_VALUE: ${{secrets.MY_SECRET_VALUE}}"
                  echo "i_dont_exist: ${{secrets.i_dont_exist}}"

