name: usingGitHubEnv

on:
  workflow_dispatch: 

jobs: 
  usingGitHubEnv:
    runs-on: windows-latest
    steps:
          - name: Set env variable
            run: |
              echo "MY_VAR=my_value" >> $GITHUB_ENV
          - name: Use env variable
            run: |
              echo "My variable is: $MY_VAR"